### ISSUE TITLE
Potential Rename

### ISSUE THREAD

**Issue by DEEKAYR** [RVRX/GoICasterCompanion#46]
okay what about branding like what if we call it Guns of Icarus Online Caster Companion (GoIOCC)!???!??!?!??!??!?!?

**Comment by RVRX** [comment]
Maybe just `GoICC` / `Guns of Icarus Caster Companion`

**Comment by RVRX** [comment]
Going Through with rename now.

**Comment by RVRX** [comment]
Done-zo, repo renamed as well
