### ISSUE TITLE
Remember team choices

### ISSUE THREAD

**Issue by DEEKAYR** [RVRX/GoICasterCompanion#71]
When I switch tabs it forget, i don't want it to forget.

**Comment by RVRX** [comment]
The solution to this would probably be just loading the current teams from their files when loading the team page

**Comment by RVRX** [comment]
Add new function `getTeam(String aTeam)`, to parse teamname from file, and add to each field. Will need to handle team file not created or empty errors. Will need to convert file text into a team object and compare with the objects inside the dropdown - as they won't be the same object in memory. Might need to make a team object comparator (`.equals` fcn)
