### ISSUE TITLE
Custom Timer Finished Text

### ISSUE THREAD

**Issue by DEEKAYR** [RVRX/GoICasterCompanion#72]
Hello maybe 0 should say lobby starting since you know the timer is done but maybe? Maybe have it as option to input custom text when timer hit zero for customizartion like in need for speed underground 2 thanks

**Comment by RVRX** [comment]
this feature will not be included in v1.0 release but may be added in subsequent updates, say when working on #12 and when cleaning the timer class

**Comment by RVRX** [comment]
Current implementation as of e60c2be, behaves as such:
When timer naturally reaches 0, custom text is applied.
When timer is stopped (from a play, paused, or stop state), the displayed text is `0:00`.

Therefore, a timer with custom text can always be overwritten to `0:00` by pressing stop.
**The alternative**, would be to have the stop button also display the custom text, OR could have a preference in settings deciding how the user would like the stop button to behave


<img width="812" alt="image" src="https://user-images.githubusercontent.com/45409688/125878660-187054c6-d213-419a-9479-b770cccca84f.png">


NOTE: In-app preview does not display the custom text as of the aforementioned commit e60c2be
